### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by FDiskas** [stegano/next-http-proxy-middleware#25]
I was using this module like so:
```ts
import httpProxyMiddleware from 'next-http-proxy-middleware';
import { NextApiRequest, NextApiResponse } from 'next';
import { getSession } from '@auth0/nextjs-auth0';
import * as Sentry from '@sentry/node';

import { initSentry } from 'src/utils/sentry';

export default async (req: NextApiRequest, res: NextApiResponse) => {
    const session = getSession(req, res);

    return new Promise((resolve) =>
        httpProxyMiddleware(req, res, {
            target: process.env.NEXT_PUBLIC_API_BASE_URL,
            headers: { Authorization: `Bearer ${session?.idToken}`, 'Content-Type': 'application/json-patch+json' },
        }).catch(async (error) => {
            initSentry();
            Sentry.captureException(error);
            await Sentry.flush(2000);

            return resolve(error);
        })
    );
};

```
And as you can see in memory usage graph it is spikes and some server restarts.
But when I switched to middleware like so
```ts
import { NextApiRequest, NextApiResponse } from 'next';
import { getSession } from '@auth0/nextjs-auth0';
import { createProxyMiddleware } from 'http-proxy-middleware';
import * as Sentry from '@sentry/node';

import { initSentry } from 'src/utils/sentry';

export const config = {
    api: {
        bodyParser: false,
        externalResolver: true,
    },
};

export default createProxyMiddleware({
    target: process.env.NEXT_PUBLIC_API_BASE_URL,
    headers: {
        'Content-Type': 'application/json-patch+json',
    },
    selfHandleResponse: false,
    changeOrigin: true,
    xfwd: true,
    secure: true,
    proxyTimeout: 3000,
    ws: true,
    onProxyReq: (proxyReq, req: Request & NextApiRequest, res: Response & NextApiResponse) => {
        proxyReq.setHeader('Authorization', `Bearer ${getSession(req, res)?.idToken}`);
    },
    onError: (err, req: Request & NextApiRequest, res: Response & NextApiResponse) => {
        initSentry();
        Sentry.captureException(err);
        Sentry.flush(2000);

        res.end('Something went wrong.');
    },
});

```
the memory usage becomes stable. Also got correct response headers from API like 404

![image](https://user-images.githubusercontent.com/468006/115832145-35e1e100-a41b-11eb-81f8-5f7e24cc6341.png)

**Comment by stegano** [comment]
Hi @FDiskas 😀

Thanks for reporting the problem.

I tried to reproduce it in my local environment, but it doesn't work.

When using this middleware, did the memory gradually increase, and was the server restarted by OOM?

Can you elaborate on the attached graph?

**Comment by FDiskas** [comment]
Hi, before the memory was slowly increasing over time. Thous spike drop downs was probably because of the restart. The project is running within a docker container in aws. Did not investigated deeper. Just noticed that during development the local server stops after some time and i need to restart it. After changing to simple middleware everything works without strange crashes.
Thous graphs is taken from aws instance metrics.

**Comment by stegano** [comment]
@FDiskas 

Thank you for the explanation. 😀

Could you tell me what version of next-http-proxy-middleware you are currently using for your project?
Prior to v1.0.10, memory leaks may have occurred when using HTTP HEAD, DELETE, CONNECT, OPTIONS, and PUT methods. 😭

**Comment by stegano** [comment]
<img width="714" alt="스크린샷 2021-04-25 오후 11 38 23" src="https://user-images.githubusercontent.com/11916476/115997782-609c8700-a61f-11eb-82e3-95f1b76a18f5.png">
<img width="657" alt="스크린샷 2021-04-25 오후 11 38 20" src="https://user-images.githubusercontent.com/11916476/115997788-63977780-a61f-11eb-8c4f-3b67b4f3e6bf.png">

It is not yet accurate, but it seems that system memory accumulates in the inspector when repeatedly requested several times using the ab test.. Let's check a little more. 🤔
Thanks for reporting.

**Comment by FDiskas** [comment]
As I noticed that there is a new release I updated as soon as possible but didn't noticed any improvement regarding memory

**Comment by stegano** [comment]
> As I noticed that there is a new release I updated as soon as possible but didn't noticed any improvement regarding memory

😭

**Comment by FDiskas** [comment]
Could be related https://github.com/stegano/next-http-proxy-middleware/issues/21

**Comment by stegano** [comment]
If possible, try applying the code like this:
(The problem I've identified is that when a promise(async) is exported, the memory increases with the increase in requests.)
```ts
// as-is
export default async (req: NextApiRequest, res: NextApiResponse) => {
    const session = getSession(req, res);

    return new Promise((resolve) =>
        httpProxyMiddleware(req, res, {
            target: process.env.NEXT_PUBLIC_API_BASE_URL,
            headers: { Authorization: `Bearer ${session?.idToken}`, 'Content-Type': 'application/json-patch+json' },
        }).catch(async (error) => {
            initSentry();
            Sentry.captureException(error);
            await Sentry.flush(2000);

            return resolve(error);
        })
    );
};
```

```ts
// to-be ✨
export default (req: NextApiRequest, res: NextApiResponse) => {
  const session = getSession(req, res);
  return httpProxyMiddleware(req, res, {
    target: process.env.NEXT_PUBLIC_API_BASE_URL,
    headers: { Authorization: `Bearer ${session?.idToken}`, 'Content-Type': 'application/json-patch+json' },
  }).catch(async (error) => {
    initSentry();
    Sentry.captureException(error);
    await Sentry.flush(2000);
  });
};
```


**Test result**

<img width="770" alt="4000requests after fix issue code" src="https://user-images.githubusercontent.com/11916476/116000296-96933880-a62a-11eb-8960-853ef1342d7c.png">

> Request sent 4000 times

```ts
// Test code
export default (req: NextApiRequest, res: NextApiResponse) => httpNextProxyMiddleware(req, res, {
  target: 'https://naver.com',
}).catch(async (error) => console.log(error));
```
- No continuous memory growth

<img width="880" alt="4000request, nested promise" src="https://user-images.githubusercontent.com/11916476/116000291-8f6c2a80-a62a-11eb-9b34-240c185014e3.png">

> Request sent 4000 times

- Memory usage is constantly increasing

```ts
// Test code
export default async (req: NextApiRequest, res: NextApiResponse) => new Promise(
  (resolve) => httpNextProxyMiddleware(req, res, {
    target: 'https://naver.com',
  }).catch(async (error) => resolve(error)),
);
```

**Comment by FDiskas** [comment]
I will try at Monday let you know

**Comment by FDiskas** [comment]
Looks like still something is wrong.
```ts
import { NextApiRequest, NextApiResponse } from 'next';
import { getSession } from '@auth0/nextjs-auth0';
import httpProxyMiddleware from 'next-http-proxy-middleware';
import * as Sentry from '@sentry/node';

import { initSentry } from 'src/utils/sentry';

export const config = {
    api: {
        bodyParser: false,
        externalResolver: true,
    },
};

export default async (req: NextApiRequest, res: NextApiResponse) => {
    const session = getSession(req, res);

    try {
        return await httpProxyMiddleware(req, res, {
            target: process.env.NEXT_PUBLIC_API_BASE_URL,
            headers: {
                Authorization: `Bearer ${session?.idToken}`,
                'Content-Type': 'application/json-patch+json',
            },
        });
    } catch (error: any) {
        initSentry();
        Sentry.captureException(error);
        await Sentry.flush(2000);

        return error?.message;
    }
};
```
And after some time I get crash
```
node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

Error: socket hang up
    at connResetException (internal/errors.js:617:14)
    at TLSSocket.socketCloseListener (_http_client.js:443:25)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  code: 'ECONNRESET'
```

**Comment by stegano** [comment]
> ```ts
> ```ts
> import { NextApiRequest, NextApiResponse } from 'next';
> import { getSession } from '@auth0/nextjs-auth0';
> import httpProxyMiddleware from 'next-http-proxy-middleware';
> import * as Sentry from '@sentry/node';
> 
> import { initSentry } from 'src/utils/sentry';
> 
> export const config = {
>     api: {
>         bodyParser: false,
>         externalResolver: true,
>     },
> };
> 
> export default async (req: NextApiRequest, res: NextApiResponse) => {
>     const session = getSession(req, res);
> 
>     try {
>         return await httpProxyMiddleware(req, res, {
>             target: process.env.NEXT_PUBLIC_API_BASE_URL,
>             headers: {
>                 Authorization: `Bearer ${session?.idToken}`,
>                 'Content-Type': 'application/json-patch+json',
>             },
>         });
>     } catch (error: any) {
>         initSentry();
>         Sentry.captureException(error);
>         await Sentry.flush(2000);
> 
>         return error?.message;
>     }
> };
> ```
> ```

Hi @FDiskas,

Do not return promise(await function) 😭

```ts
export default async (req: NextApiRequest, res: NextApiResponse) => { // <-- `fix to export default (req: NextApiRequest, res: NextApiResponse)`
    const session = getSession(req, res);

    try {
        return await httpProxyMiddleware(req, res, { // <-- fix to `return httpProxyMiddleware`
            target: process.env.NEXT_PUBLIC_API_BASE_URL,
            headers: {
                Authorization: `Bearer ${session?.idToken}`,
                'Content-Type': 'application/json-patch+json',
            },
        });
    } catch (error: any) {
        initSentry();
        Sentry.captureException(error);
        await Sentry.flush(2000);

        return error?.message;
    }
};
```

**Comment by FDiskas** [comment]
The reason is simple. Eslint rules does that. :) But I will check later that

**Comment by FDiskas** [comment]
Tested - still memory is increasing - I used code like so
```tsx
export const config = {
    api: {
        bodyParser: false,
        externalResolver: true,
    },
};

export default (req: NextApiRequest, res: NextApiResponse) => {
    return httpProxyMiddleware(req, res, {
        preserveHeaderKeyCase: true,
        target: process.env.NEXT_PUBLIC_API_BASE_URL,
        timeout: 3000,
        headers: {
            'Content-Type': 'application/json-patch+json',
        },
    }).catch(async (error) => {
        res.end(error.message);
    });
};
```
I builded app and then started it using 
```
NODE_OPTIONS='--inspect' next start
```
attached chrome inspector and I compared between memory snapshots and the main issue is pointing to `next-http-proxy-middleware`
sorry forgot to take a screenshots

**Comment by FDiskas** [comment]
And after reverting it back to http-proxy-middleware I got something better. It is still growing but this time a different plugin.

![image](https://user-images.githubusercontent.com/468006/118173942-e51c4180-b436-11eb-9f26-b5643164541c.png)

**Comment by stegano** [comment]
> Tested - still memory is increasing - I used code like so
> 
> ```tsx
> export const config = {
>     api: {
>         bodyParser: false,
>         externalResolver: true,
>     },
> };
> 
> export default (req: NextApiRequest, res: NextApiResponse) => {
>     return httpProxyMiddleware(req, res, {
>         preserveHeaderKeyCase: true,
>         target: process.env.NEXT_PUBLIC_API_BASE_URL,
>         timeout: 3000,
>         headers: {
>             'Content-Type': 'application/json-patch+json',
>         },
>     }).catch(async (error) => {
>         res.end(error.message);
>     });
> };
> ```
> 
> I builded app and then started it using
> 
> ```
> NODE_OPTIONS='--inspect' next start
> ```
> 
> attached chrome inspector and I compared between memory snapshots and the main issue is pointing to `next-http-proxy-middleware`
> 
> ![image](https://user-images.githubusercontent.com/468006/118172651-4a6f3300-b435-11eb-8b5b-c66db7c534cb.png)

When I checked before, it was confirmed that it was a problem with the code your wrote, not the next-http-proxy-middleware problem (https://github.com/stegano/next-http-proxy-middleware/issues/25#issuecomment-826349635 )

JS memory can grow and shrink while the process is running. Over time, unused memory is removed by the GC.

In the case above, is there an error response when requesting through a proxy?

Clear async in the catch clause and try again.

If the catch does not return a promise result, the promise will not be removed by the GC and will persist.

**Comment by FDiskas** [comment]
Thank you for good explanation.
In this case no errors in requests was thrown. But as you said probably I need to ignore such small memory changes.
Can we have a good working example in a repository?

**Comment by stegano** [comment]
> Thank you for good explanation.
> In this case no errors in requests was thrown. But as you said probably I need to ignore such small memory changes.
> Can we have a good working example in a repository?

This library can be used in a variety of ways, making it difficult to give specific examples. However, if a good reference is recorded like this issue, I think I can refer to it later.
